version: 1.0.{build}
image: Visual Studio 2019
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
build: off
install:
    - dir "C:\Program Files\LLVM\bin"
    - dir "C:\Program Files\LLVM\lib"
    - set LLVM_SYS_110_PREFIX="C:\Program Files\LLVM\"
    - echo %LLVM_SYS_110_PREFIX%
    - pushd llvm-example
    - cargo run --release
    - popd
    - md build\Release\include
    - set LLVM_SYS_110_PREFIX=%cd%\build\Release
    - echo %LLVM_SYS_110_PREFIX%
    - curl -O -L https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz
    - 7z e -y llvm-11.1.0.src.tar.xz
    - 7z x -y llvm-11.1.0.src.tar
    - cp -r llvm-11.1.0.src\include\llvm-c build\Release\include
build_script:
    - pushd build
    - >-
        cmake.exe
        -DCMAKE_BUILD_TYPE=Release
        -DLLVM_INCLUDE_TOOLS=ON
        -DLLVM_OPTIMIZED_TABLEGEN=ON
        -DLLVM_INCLUDE_EXAMPLES=OFF
        -DLLVM_INCLUDE_TESTS=OFF
        -DLLVM_INCLUDE_GO_TESTS=OFF
        -DLLVM_INCLUDE_UTILS=OFF
        -DLLVM_ENABLE_ZLIB=OFF
        -DLLVM_ENABLE_TERMINFO=OFF
        ./../llvm-11.1.0.src/
    - msbuild -m /p:Configuration=Release llvm-headers.vcxproj
    - dir Release\lib
    - dir Release\bin
    - cp -r include\llvm Release\include
    - 7z a llvm-11.1.0-windows.zip Release
    - popd
    - pushd llvm-example
    - cargo run --release
artifacts:
    - path: build\llvm-11.1.0-windows.zip
