version: 1.0.{build}
image: Visual Studio 2019
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
build: off
install:
    - wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz
    - 7z e -y llvm-11.1.0.src.tar.xz
    - 7z x -y llvm-11.1.0.src.tar
    - where cmake
build_script:
    - md build
    - pushd build
    - cmake.exe ./../llvm-11.1.0.src/
    - msbuild -m /p:Configuration=Release llvm-headers.vcxproj
    - popd
